// clientes/livros-react/src/LivroDados.js
import {  useState } from "react";
import { Navigate } from "react-router-dom";
 
import ControleLivros from "./controle/ControleLivros"; 
import ControleEditora from "./controle/ControleEditora";
 
import { Livro } from "./modelo/Livro";
 
import './styles/LivroDados.css'


export default function LivroDados() {
  const controleEditora = new ControleEditora();
   
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [editora,setEditora]= useState("")
  
  const [autoresInput, setAutoresInput] = useState("");

  const [redirect, setRedirect] = useState(false);
   
  const editoras = controleEditora.getEditoras();
  const opcoes = editoras.map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));
 
  const enviarDados=(ev)=>{
   
    ev.preventDefault()  
    
    // autores
    
    var autores=[]
    var valoresSeparados = autoresInput.split("\n")
    var autoresArray = valoresSeparados.map((autor) => autor.trim())
    autoresArray.map((autor)=>{autores.push(autor)})
    ;
    
    //Editora

    const editoraSelecionada=opcoes.filter(opcao=>opcao.text===editora)  
 
    let livro= new Livro(0,editoraSelecionada[0].value ,titulo,resumo,autores)
    
    const ctrLivros = new ControleLivros()
    console.log('dentro de livro dados livro.titulo : ',livro.titulo)
    ctrLivros.incluir(livro)
 
    setRedirect(true) 
 
  }
  

  return (
    <div>
        {redirect && <Navigate to="/" />}
          
        <div className="container">
        <h1>Dados do Livro</h1>
        <form>
          <div className="form-group">
            <label htmlFor="titulo">Titulo</label>
            <input
              type="text"
              className="form-control"
              id="titulo"
              placeholder="Digite o titulo"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label htmlFor="resumo">Resumo</label>
            <textarea
              className="form-control"
              id="resumo"
              rows="3"
              placeholder="Digite o resumo"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
            />
          </div>
          <div className="form-group">
            <label htmlFor="editora">Editora</label>
            <select
              className="form-control"
              id="editora"
              value={editora}
              placeholder="seleciona a editora"
              onChange={(e) => setEditora(e.target.value)}
            >
              <option key={0}></option> 
              {opcoes.map((editora, index) => (
                <option key={editora.value}>{editora.text}</option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label htmlFor="autores">Autores</label>
            <textarea
              className="form-control"
              id="autores"
              placeholder="Digite o(s) autor(es)"
              value={autoresInput}
              onChange={(e) => setAutoresInput(e.target.value)}
               
            />
          </div>
          </form>        
           <button id="button" onClick={enviarDados} className="btn btn-primary">
            Salvar dados
          </button>
 
         
      </div>
       
    </div>
  );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Livro } from '../livro';
import { Editora } from '../editora';

import { Component, OnInit } from '@angular/core';

import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import {Router } from '@angular/router';
@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],

})
export class LivroDadosComponent implements OnInit{

  private router:Router;
  private servEditora:ControleEditoraService;
  private servLivros:ControleLivrosService;

  autoresForm:string='';
  editoras :Editora[]=[];

  livro:any = { titulo:'',resumo: '',editoraNome:'',autores:[] };

  constructor(
    servEditora:ControleEditoraService,
    servLivros:ControleLivrosService,
    router:Router)
    {
    this.router=router;
    this.servEditora=servEditora;
    this.servLivros=servLivros;
    }

        ngOnInit(): void {
        this.editoras=this.servEditora.getEditoras()
        //console.log('this.editoras',this.editoras)
    }


    incluir=()=>{
      //editora
      const editoraSelecionada=this.editoras.filter(editora=>editora.nome===this.livro.editoraNome)
      //

      // autores
      var autores:string[]=[]
      var valoresSeparados = this.livro.autores.split("\n")
      var autoresArray = valoresSeparados.map((autor:any) => autor.trim())
      autoresArray.map((autor:any)=>{autores.push(autor)})

      console.log('autores',autores)
      var livro= new Livro(
                 '0',
                 editoraSelecionada[0].codEditora,
                 this.livro.titulo,
                 this.livro.resumo,
                 autores )

       this.servLivros.incluir(livro)
       this.router.navigateByUrl('/')
    }

 }

<div class="container">
  <form>
    <div class="form-group">
      <label htmlFor="titulo">Titulo</label>
      <input
        type="text"
        class="form-control"
        id="titulo"
        name="titulo"
        placeholder="Digite o titulo"
        [(ngModel)]="livro.titulo"/>
    </div>

    <div class="form-group">
      <label htmlFor="resumo">Resumo</label>
       <textarea
        class="form-control"
        id="resumo"
        name="resumo"
        placeholder="Digite o resumo"
        [(ngModel)]="livro.resumo"></textarea>

    </div>
    <div class="form-group">
      <label htmlFor="editora">Editora</label>
      <select
        class="form-control"
        id="editora"
        name="editora"
        [(ngModel)]="livro.editoraNome"
        placeholder="seleciona a editora">
        <option key={0}></option>
        <option *ngFor="let editora of editoras" [value]="editora.nome">
          {{ editora.nome }}</option>

      </select>
    </div>
    <div class="form-group">
      <label htmlFor="autores">Autores</label>
      <textarea
        class="form-control"
        id="autores"
        name="autores"
        placeholder="Digite o(s) autor(es)"
        [(ngModel)]="livro.autores"></textarea>
    </div>
  </form>
  <div class="xx">
    <button id="button"  class="btn btn-primary" (click)="incluir()">
      Salvar dados
    </button>

  </div>
</div>
